"""Generate README.md's "Worked examples" section from the real engine and
agent (CLAUDE.md: "README worked examples must be generated by the engine,
never typed by hand"). Run with: uv run python scripts/generate_readme_examples.py
"""

from __future__ import annotations

import re
from pathlib import Path

from backend.agent.orchestrator import AgentOrchestrator, ScriptedLLM
from backend.agent.schemas import AgentPlan
from backend.engine.batch import evaluate_batch
from backend.engine.scenario import Lever, Scenario
from backend.model.spec import build_param_draws

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"

START = "<!-- BEGIN GENERATED WORKED EXAMPLES -->"
END = "<!-- END GENERATED WORKED EXAMPLES -->"

AURORA_CAN = "Aurora-can_330ml"


def _fmt(band) -> str:
    return f"{band.value:,.0f} (p10 {band.p10:,.0f} / p90 {band.p90:,.0f})"


def engine_example() -> str:
    draws = build_param_draws(k=200, seed=1000)
    scenarios = [
        Scenario(name="Baseline"),
        Scenario(name="+5% price on Aurora can", levers={AURORA_CAN: Lever(price_index=1.05)}),
        Scenario(
            name="20% TPR promo on Aurora can",
            levers={
                AURORA_CAN: Lever(promo_depth_pct=20.0, mechanic="TPR", promo_weeks_per_month=2.0)
            },
        ),
        Scenario(
            name="Price index 3.0 on Aurora can (out of range)",
            levers={AURORA_CAN: Lever(price_index=1.8)},
        ),
    ]
    results = evaluate_batch(scenarios, draws)

    lines = [
        "### Engine: price vs. promo on one SKU",
        "",
        "Generated by `scripts/generate_readme_examples.py` against the real engine "
        f"(`evaluate_batch`, K={draws.k} draws, seed={draws.seed}). Figures are Modeled, "
        "not observed — every number traces to `backend.engine.batch.evaluate_batch`.",
        "",
        "| Scenario | Status | Aurora weekly gross profit, INR (central / p10 / p90) |",
        "|---|---|---|",
    ]
    for scenario, result in zip(scenarios, results, strict=True):
        if result.status == "REFUSED":
            reasons = (
                "; ".join(r.get("message", str(r)) for r in result.refusal_reasons)
                or "out of supported range"
            )
            lines.append(f"| {scenario.name} | REFUSED | no numeric fields ({reasons}) |")
        else:
            b = result.focal["gp"]
            lines.append(f"| {scenario.name} | {result.status} | {_fmt(b)} |")
    lines.append("")
    return "\n".join(lines)


def agent_example() -> str:
    scenarios = [
        Scenario(name="Baseline"),
        Scenario(name="+5% price on Aurora can", levers={AURORA_CAN: Lever(price_index=1.05)}),
        Scenario(
            name="20% TPR promo on Aurora can",
            levers={
                AURORA_CAN: Lever(promo_depth_pct=20.0, mechanic="TPR", promo_weeks_per_month=2.0)
            },
        ),
        Scenario(
            name="Price index 3.0 on Aurora can (out of range)",
            levers={AURORA_CAN: Lever(price_index=1.8)},
        ),
    ]
    plan = AgentPlan(scenarios=scenarios)
    run = AgentOrchestrator().run(
        "Compare a price rise against a promo on Aurora can.", ScriptedLLM(plan)
    )

    lines = [
        "### Agent: same scenarios, through the agent loop",
        "",
        "Generated by the same script, running the scripted deterministic agent "
        "(`AgentOrchestrator` + `ScriptedLLM`, same tools a live Claude/OpenAI run uses) "
        "over the same four scenarios. Every claim below is grounded and labelled by the "
        "real Auditor, not typed by hand.",
        "",
        f"- Auditor verdict: **{'PASSED' if run.audit.passed else 'FAILED'}**",
        "",
        "| Claim | Label |",
        "|---|---|",
    ]
    for claim in run.answer.claims:
        lines.append(f"| {claim.text} | {claim.label} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    body = engine_example() + "\n" + agent_example()
    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    replacement = f"{START}\n{body}\n{END}"
    if pattern.search(text):
        text = pattern.sub(replacement, text)
    else:
        text = text.rstrip() + "\n\n## Worked examples\n\n" + replacement + "\n"
    README.write_text(text, encoding="utf-8")
    print("README.md worked examples regenerated.")


if __name__ == "__main__":
    main()
